### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by RalfJung** [minirust/minirust#10]
We don't support encoding or decoding enums yet. Some interesting questions will arise when adding them.

Relevant material:
- https://github.com/camelid/type-layout by @camelid
- [a very WIP writeup](https://hackmd.io/@2S4Crel_Q9OwC_vamlwXmw/By4FoVud9) by @JakobDegen suggesting "DSLs" for describing very general encoding and decoding strategies for enums

**Comment by essickmango** [comment]
Support for enums was added in the following PRs:

- [Enum variant ValueExpr](https://github.com/minirust/minirust/pull/143)
- [Enum memory representation and well-formedness](https://github.com/minirust/minirust/pull/146)
- [Enum Downcast](https://github.com/minirust/minirust/pull/148)
- [Enum GetDiscriminant and SetDiscriminant](https://github.com/minirust/minirust/pull/149)
- [Switch terminator](https://github.com/minirust/minirust/pull/150)
- [Alignment-check fixes (mainly around enums)](https://github.com/minirust/minirust/pull/151)
- [Changes to discriminant handling](https://github.com/minirust/minirust/pull/153)
- [Minimize support for everything enum related but niche tag encoding](https://github.com/minirust/minirust/pull/152)
- [Minimize support for niche tag encoded enums](https://github.com/minirust/minirust/pull/154)

Currently the only enums that cannot be minimized are exponentially nested enums (each enum has four variants with one field of the nested enum, see `tests/pass/enums.rs`) due to minimize always recompiling the type, and `Option<NonZeroINT>::None`, which gets transformed into a Scalar Value that minimize would have to parse.

**Comment by RalfJung** [comment]
One point I recently noticed is still missing is enums inside unions: `mark_used_bytes` does not support enums yet.

**Comment by RalfJung** [comment]
> and Option<NonZeroINT>::None, which gets transformed into a Scalar Value that minimize would have to parse.

That issue is tracked separately in https://github.com/minirust/minirust/issues/158.

**Comment by RalfJung** [comment]
I opened https://github.com/minirust/minirust/issues/167 for the enum-in-union issue. This one here can be closed then, thanks to @essickmango. :)
