### ISSUE TITLE
enums in unions trigger "unsupported" error

### ISSUE THREAD

**Issue by RalfJung** [minirust/minirust#167]
Testcase:
```rust
fn enum_in_union() {
    #[derive(Clone, Copy)]
    enum MyBool { MyTrue, MyFalse }

    union Bools { my: MyBool, theirs: bool }

    let _val = Bools { theirs: true };
    let _val = Bools { my: MyBool::MyFalse };
}
```

This is caused by `mark_used_bytes` not being able to handle enums.

**Comment by essickmango** [comment]
I have an implementation ready [here](https://github.com/essickmango/minirust/tree/enum_mark_used_bytes), and will open a PR after I thought a bit about how to test for this or to leave it at that.

**Comment by essickmango** [comment]
I agree with adding the discriminator, I didn't even think of it as it really should be equivalent tbh.

I thought I would add some more tests for nested structs and arrays as well, and it seems like structs cause the union to not be well-formed.

Regarding the failing test: The gap in `Option<(i8, i16)>` would be used for the discriminant so that would work fine. And as soon as I produce the gap with `repr(i16)` then I get well-formedness issues again. They seem to be with ADTs that have gaps in general?

**Comment by essickmango** [comment]
Oh, found the issue: Every field needs to fit into a single chunk at the moment. This seems wrong considering that the types in the fields may have inside padding.

**Comment by RalfJung** [comment]
The gap in option<(u8, u16)> cannot be used for the discriminant. Padding of inner fields can be overwritten when taking a reference to the field and assigning to it, so it cannot be used to store the discriminat.

**Comment by RalfJung** [comment]
Note that `Option<(u8, u16)>` is not the same as `enum E { V1(u8, u16), V2 }`. The fact that `(u8, u16)` are wrapped in a tuple makes a difference.

> Oh, found the issue: Every field needs to fit into a single chunk at the moment. This seems wrong considering that the types in the fields may have inside padding.

I don't know what you mean by this. `mark_used_bytes` computes a bitmask, it doesn't care about "fields". The part of `calc_chunks` that processes that bitmask does not need any changes for enums.

**Comment by essickmango** [comment]
> Note that Option<(u8, u16)> is not the same as enum E { V1(u8, u16), V2 }. The fact that (u8, u16) are wrapped in a tuple makes a difference.

True, I confused the two.

> I don't know what you mean by this. mark_used_bytes computes a bitmask, it doesn't care about "fields". The part of calc_chunks that processes that bitmask does not need any changes for enums.

For each field `(ty, offset)` the following well-formedness check is done in the spec:
```rust
ensure(chunks.any(|(chunk_offset, chunk_size)| {
    chunk_offset <= offset
        && offset + ty.size::<T>() <= chunk_offset + chunk_size
}))?;
```
This means that each field needs to be covered by a single chunk. This obviously fails if a tuple/struct/enum variant has a gap of padding which produces two chunks.

My suggestion to fix this: move the `mark_used_bytes` into the spec, and use it to ensure that each used byte of the type in the field is covered by some chunk. Because the existing well-formedness check for the fields being covered by a single chunk does not make sense to me if I understand the semantics of unions correctly from the linked Rust discussions.

**Comment by RalfJung** [comment]
That WF check indeed seems wrong and broken already without enums... i will take a look.

**Comment by RalfJung** [comment]
I have removed that check, and added a testcase that was broken before removing it.

**Comment by essickmango** [comment]
Is that intentional behavior to not check that data bytes in the end are covered by chunks? That would mean that a union with inhabited fields but no chunks is well-formed. Or is the preservation of data ensured by minimize and the check therefore not needed?

**Comment by essickmango** [comment]
Regardless of this (I don't see anymore how it relates to this issue), I have a PR here: https://github.com/minirust/minirust/pull/168

**Comment by RalfJung** [comment]
Yeah if you define a union type with no chunks, it will lose all data on copies. That's your problem...

Not sure if it's worth having a check for that in WF. :shrug:
